name: unpapered
description: "A mobile application to chat with PDF"

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  lottie: ^3.1.0
  svg_flutter: ^0.0.1
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.1.0
  dash_chat_2: ^0.0.20
  http: ^1.2.0
  flutter_shakemywidget: ^1.0.5+1
  iconsax: ^0.0.8
  file_picker: ^6.1.1
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_native_splash: ^2.3.10
  connectivity_plus: ^5.0.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  web_socket_channel: ^2.4.4
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.12
  animated_text_kit: ^4.2.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/logos/
    - assets/onboard/
    - assets/email/
    - assets/home/
    - assets/sadie/
    - assets/load/
    - assets/popup/